version: '3.8'
services:
  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://app-db:5432/Bookstore
      -user=postgres
      -password=06082009bQ
      -schemas=public
      -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/flyway/sql/:/flyway/sql/
    restart: on-failure
    depends_on:
      app-db:
        condition: service_healthy
  app-db:
    image: postgres
    restart: unless-stopped
    container_name: 'java-postgres'
    environment:
      - POSTGRES_DB=Bookstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=06082009bQ
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 3
  app:
    build: .
    container_name: 'java-app'
    ports:
      - '8080:8080'
    volumes:
      - postgres_data:/var/lib/postgresql
    depends_on:
      app-db:
        condition: service_healthy
volumes:
  postgres_data: